# Generated by Django 5.2.5 on 2025-08-23 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
