# Generated by Django 5.0.6 on 2025-11-02 04:08

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_image_retry_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.image_upload_to),
        ),
    ]
