# Generated by Django 5.2.7 on 2026-01-29 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_imageembedding_vector_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.imagecomment'),
        ),
        migrations.AlterField(
            model_name='imageembedding',
            name='image_embedding_json',
            field=models.JSONField(blank=True, help_text='Fallback: image embedding as JSON list when pgvector unavailable', null=True),
        ),
        migrations.AlterField(
            model_name='imageembedding',
            name='prompt_embedding_json',
            field=models.JSONField(blank=True, help_text='Fallback: prompt embedding as JSON list when pgvector unavailable', null=True),
        ),
        migrations.AlterField(
            model_name='imageembedding',
            name='prompt_text',
            field=models.TextField(blank=True, help_text='The prompt text used to generate the embedding (for debugging/analysis)'),
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='api.imagecomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('comment', 'user'), name='unique_like_per_user_comment')],
            },
        ),
    ]
