# Generated by Django 6.0.4 on 2026-04-13 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_creativesession_sessionmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='generation_type',
            field=models.CharField(choices=[('txt2img', 'Text to Image'), ('img2img', 'Image to Image'), ('variation', 'Variation'), ('restyle', 'Restyle'), ('upscale', 'Upscale')], default='txt2img', max_length=20),
        ),
        migrations.AddField(
            model_name='image',
            name='source_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivatives', to='api.image'),
        ),
        migrations.AddField(
            model_name='image',
            name='strength',
            field=models.FloatField(blank=True, help_text='Transformation strength 0.0-1.0 for img2img', null=True),
        ),
    ]
