# Generated by Django 5.0.6 on 2025-11-02 03:15

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_reset_date',
            field=models.DateField(default=authentication.models.current_date),
        ),
    ]
