# Generated by Django 5.2.7 on 2025-11-02 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_user_last_reset_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
