version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: imagaine-frontend
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - imagaine-network

networks:
  imagaine-network:
    driver: bridge
