/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/account/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Deletar conta
         * @description Deleta permanentemente a conta do usuário e todas as suas imagens. Requer confirmação com a senha atual. Ação irreversível.
         */
        delete: operations["auth_account_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Autentica o usuário e retorna par de tokens JWT (access + refresh).
         */
        post: operations["auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password/change/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trocar senha
         * @description Altera a senha do usuário autenticado. Requer a senha atual.
         */
        post: operations["auth_password_change_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password/reset/confirm/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirmar reset de senha
         * @description Valida o token e define nova senha.
         */
        post: operations["auth_password_reset_confirm_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password/reset/request/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Solicitar reset de senha
         * @description Envia email com link de reset. Não revela se o email existe.
         */
        post: operations["auth_password_reset_request_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/preferences/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obter preferências
         * @description Retorna as preferências salvas do usuário (JSON livre).
         */
        get: operations["auth_preferences_retrieve"];
        /**
         * Atualizar preferências
         * @description Substitui as preferências do usuário por um objeto JSON.
         */
        put: operations["auth_preferences_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/profile/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description View to retrieve and update user profile. */
        get: operations["auth_profile_retrieve"];
        /** @description View to retrieve and update user profile. */
        put: operations["auth_profile_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description View to retrieve and update user profile. */
        patch: operations["auth_profile_partial_update"];
        trace?: never;
    };
    "/api/auth/profile/avatar/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload de avatar
         * @description Envia ou substitui a foto de perfil do usuário.
         */
        post: operations["auth_profile_avatar_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/profile/cover/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload de capa
         * @description Envia ou substitui a imagem de capa do usuário.
         */
        post: operations["auth_profile_cover_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description View for user registration. */
        post: operations["auth_register_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/token/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid.
         */
        post: operations["auth_token_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verify-email/{token}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Verificar email
         * @description Valida o token de verificação enviado por email. Token expira em 24h.
         */
        get: operations["auth_verify_email_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/generate/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Gerar imagem
         * @description Envia um prompt para geração assíncrona de imagem via FLUX.1-dev. A imagem é criada com status GENERATING e transiciona para READY ou FAILED. Respeita a quota mensal do plano do usuário.
         */
        post: operations["generate_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/{id}/comments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["images_comments_list"];
        put?: never;
        post: operations["images_comments_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/{id}/comments/{comment_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["images_comments_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/{id}/comments/{comment_id}/like/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Curtir comentário
         * @description Adiciona um like ao comentário.
         */
        post: operations["images_comments_like_create"];
        /**
         * Descurtir comentário
         * @description Remove o like do comentário.
         */
        delete: operations["images_comments_like_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/{id}/download/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Download de imagem
         * @description Incrementa o contador de downloads e retorna a URL para download.
         */
        post: operations["images_download_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/{id}/like/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Curtir imagem
         * @description Adiciona um like à imagem. Idempotente: se já curtiu, retorna 200.
         */
        post: operations["images_like_create"];
        /**
         * Descurtir imagem
         * @description Remove o like da imagem.
         */
        delete: operations["images_like_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/{id}/related/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Imagens relacionadas
         * @description Retorna até 12 imagens similares baseadas em embeddings vetoriais. Usa image embedding (visual) com fallback para prompt embedding (texto). A imagem-fonte deve ser pública ou pertencer ao usuário.
         */
        get: operations["images_related_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/{id}/restyle/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mudar estilo
         * @description Aplica um estilo diferente a uma imagem existente. O prompt original é combinado com modificadores do estilo escolhido.
         */
        post: operations["images_restyle_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/{id}/share/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publicar imagem
         * @description Torna a imagem pública na galeria.
         */
        post: operations["images_share_create"];
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Alterar visibilidade
         * @description Altera o status público/privado da imagem.
         */
        patch: operations["images_share_partial_update"];
        trace?: never;
    };
    "/api/images/{id}/variations/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Gerar variações
         * @description Gera 1-4 variações de uma imagem existente usando img2img. O strength controla o quanto a variação difere do original (0.1 = quase igual, 0.95 = muito diferente).
         */
        post: operations["images_variations_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/liked/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["images_liked_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/my-images/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["images_my_images_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/public/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["images_public_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar projetos
         * @description Lista projetos do usuário autenticado.
         */
        get: operations["projects_list"];
        put?: never;
        /**
         * Criar projeto
         * @description Cria um novo projeto vazio.
         */
        post: operations["projects_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detalhe do projeto
         * @description Retorna o projeto com todas as imagens ordenadas.
         */
        get: operations["projects_retrieve"];
        /**
         * Atualizar projeto
         * @description Atualiza título, descrição ou visibilidade do projeto.
         */
        put: operations["projects_update"];
        post?: never;
        /**
         * Deletar projeto
         * @description Deleta o projeto. Imagens não são deletadas, apenas desassociadas.
         */
        delete: operations["projects_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/images/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Adicionar imagem ao projeto
         * @description Associa uma imagem existente ao projeto com ordem e legenda.
         */
        post: operations["projects_images_create"];
        /**
         * Remover imagem do projeto
         * @description Desassocia uma imagem do projeto (não deleta a imagem).
         */
        delete: operations["projects_images_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/images/{image_id}/remove/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Adicionar imagem ao projeto
         * @description Associa uma imagem existente ao projeto com ordem e legenda.
         */
        post: operations["projects_images_remove_create"];
        /**
         * Remover imagem do projeto
         * @description Desassocia uma imagem do projeto (não deleta a imagem).
         */
        delete: operations["projects_images_remove_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}/images/reorder/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Reordenar imagens
         * @description Reordena as imagens do projeto com base na lista de IDs fornecida.
         */
        patch: operations["projects_images_reorder_partial_update"];
        trace?: never;
    };
    "/api/projects/public/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List public projects. */
        get: operations["projects_public_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/refine-prompt/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refinar prompt
         * @description Transforma uma descrição casual em um prompt otimizado para geração de imagem. Usa o DeepSeek LLM para gerar prompt em inglês com modificadores técnicos.
         */
        post: operations["refine_prompt_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar sessões
         * @description Lista sessões criativas do usuário, ordenadas por última atualização.
         */
        get: operations["sessions_list"];
        put?: never;
        /**
         * Criar sessão
         * @description Cria uma nova sessão criativa.
         */
        post: operations["sessions_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detalhe da sessão
         * @description Retorna a sessão com todas as mensagens.
         */
        get: operations["sessions_retrieve"];
        put?: never;
        post?: never;
        /**
         * Arquivar sessão
         * @description Arquiva a sessão criativa.
         */
        delete: operations["sessions_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{id}/messages/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enviar mensagem
         * @description Envia uma mensagem ao agente criativo. O agente responde com texto e, opcionalmente, gera uma imagem se tiver informação suficiente. Usa o DeepSeek LLM para a conversa e FLUX.1-dev para geração.
         */
        post: operations["sessions_messages_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/token/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a set of user credentials and returns an access and refresh JSON web
         *     token pair to prove the authentication of those credentials.
         */
        post: operations["token_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/token/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid.
         */
        post: operations["token_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/token/verify/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a token and indicates if it is valid.  This view provides no
         *     information about a token's fitness for a particular use.
         */
        post: operations["token_verify_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/style-suggestions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sugestões de estilo
         * @description Analisa o histórico de prompts do usuário para identificar padrões recorrentes de estilo, modificadores e temas. Retorna até 5 sugestões.
         */
        get: operations["users_me_style_suggestions_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AgentResponse: {
            message: components["schemas"]["SessionMessage"];
            agent_response: components["schemas"]["SessionMessage"];
        };
        /**
         * @description * `1:1` - 1:1
         *     * `16:9` - 16:9
         *     * `4:3` - 4:3
         *     * `9:16` - 9:16
         *     * `3:2` - 3:2
         * @enum {string}
         */
        AspectRatioEnum: "1:1" | "16:9" | "4:3" | "9:16" | "3:2";
        /** @description Serializer for changing password while logged in. */
        ChangePasswordRequest: {
            current_password: string;
            new_password: string;
            new_password_confirm: string;
        };
        CommentLikeResponse: {
            comment_id: number;
            is_liked: boolean;
            like_count: number;
        };
        CommentUnlikeResponse: {
            comment_id: number;
            is_liked: boolean;
            like_count: number;
        };
        CreativeSession: {
            /** Format: uuid */
            readonly id: string;
            readonly user: components["schemas"]["ImageUser"];
            title?: string;
            status?: components["schemas"]["SessionStatusEnum"];
            readonly messages: components["schemas"]["SessionMessage"][];
            readonly message_count: number;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /** @description Lighter serializer for session lists (no messages). */
        CreativeSessionList: {
            /** Format: uuid */
            readonly id: string;
            readonly title: string;
            readonly status: components["schemas"]["SessionStatusEnum"];
            readonly message_count: number;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        DetailResponse: {
            detail: string;
        };
        DownloadResponse: {
            /** Format: uri */
            download_url: string;
            download_count: number;
        };
        GenerateError: {
            prompt?: string[];
        };
        GenerateImageRequest: {
            prompt: string;
            negative_prompt?: string | null;
            /** @default 1:1 */
            aspect_ratio: components["schemas"]["AspectRatioEnum"];
            seed?: number | null;
        };
        /**
         * @description * `txt2img` - Text to Image
         *     * `img2img` - Image to Image
         *     * `variation` - Variation
         *     * `restyle` - Restyle
         *     * `upscale` - Upscale
         * @enum {string}
         */
        GenerationTypeEnum: "txt2img" | "img2img" | "variation" | "restyle" | "upscale";
        Image: {
            readonly id: number;
            readonly user: components["schemas"]["ImageUser"];
            prompt?: string | null;
            negative_prompt?: string | null;
            aspect_ratio?: components["schemas"]["AspectRatioEnum"];
            /** Format: int64 */
            seed?: number | null;
            /** Format: uri */
            readonly image_url: string | null;
            readonly status: components["schemas"]["ImageStatusEnum"];
            is_public?: boolean;
            readonly like_count: number;
            readonly comment_count: number;
            readonly download_count: number;
            readonly is_liked: boolean;
            /** Format: double */
            readonly relevance_score: number;
            readonly featured: boolean;
            readonly tags: string[];
            readonly source_image: number | null;
            readonly generation_type: components["schemas"]["GenerationTypeEnum"];
            /**
             * Format: double
             * @description Transformation strength 0.0-1.0 for img2img
             */
            readonly strength: number | null;
            /** Format: date-time */
            readonly created_at: string;
        };
        ImageComment: {
            readonly id: number;
            readonly user: components["schemas"]["ImageUser"];
            text: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            readonly like_count: number;
            readonly is_liked: boolean;
            readonly parent_id: number | null;
            readonly reply_count: number;
            readonly replies: components["schemas"]["ImageCommentReply"][];
        };
        ImageCommentCreate: {
            text: string;
            parent_id?: number | null;
        };
        ImageCommentCreateRequest: {
            text: string;
            parent_id?: number | null;
        };
        /** @description Simplified serializer for replies (no nested replies). */
        ImageCommentReply: {
            readonly id: number;
            readonly user: components["schemas"]["ImageUser"];
            readonly text: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            readonly like_count: number;
            readonly is_liked: boolean;
        };
        /**
         * @description * `GENERATING` - Generating
         *     * `READY` - Ready
         *     * `FAILED` - Failed
         * @enum {string}
         */
        ImageStatusEnum: "GENERATING" | "READY" | "FAILED";
        /** @description Serializer resumido do usuário para contexto de imagens. */
        ImageUser: {
            /** Format: uuid */
            readonly id: string;
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            username: string;
        };
        LikeNotFound: {
            detail: string;
        };
        LoginResponse: {
            refresh: string;
            access: string;
            user: components["schemas"]["User"];
        };
        NotFound: {
            error: string;
        };
        PaginatedImageCommentList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["ImageComment"][];
        };
        PaginatedImageList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Image"][];
        };
        PaginatedProjectList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Project"][];
        };
        /** @description Serializer for password reset confirmation. */
        PasswordResetConfirmRequest: {
            /** Format: uuid */
            token: string;
            new_password: string;
            new_password_confirm: string;
        };
        /** @description Serializer for password reset request. */
        PasswordResetRequestRequest: {
            /** Format: email */
            email: string;
        };
        PatchedImageShareUpdateRequest: {
            is_public?: boolean;
        };
        PatchedProjectReorderRequest: {
            /** @description Lista ordenada de IDs de imagens no projeto */
            image_ids?: number[];
        };
        /** @description Serializer for user details. */
        PatchedUserRequest: {
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            username?: string;
            first_name?: string;
            last_name?: string;
            bio?: string;
            profile_picture?: string | null;
            cover_picture?: string | null;
            preferences?: unknown;
        };
        Project: {
            /** Format: uuid */
            readonly id: string;
            readonly user: components["schemas"]["ImageUser"];
            title: string;
            description?: string;
            cover_image?: number | null;
            /** Format: uri */
            readonly cover_image_url: string | null;
            is_public?: boolean;
            readonly tags: string[];
            readonly images: components["schemas"]["ProjectImage"][];
            readonly image_count: number;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        ProjectCreateRequest: {
            title: string;
            /** @default  */
            description: string;
        };
        ProjectImage: {
            readonly id: number;
            readonly image: components["schemas"]["Image"];
            order?: number;
            caption?: string;
            /** Format: date-time */
            readonly created_at: string;
        };
        ProjectImageAddRequest: {
            image_id: number;
            /** @default 0 */
            order: number;
            /** @default  */
            caption: string;
        };
        ProjectImageAdded: {
            id: number;
            image_id: number;
            order: number;
            caption: string;
        };
        QuotaExceeded: {
            detail: string;
        };
        /** @description Serializer for prompt refinement request. */
        RefinePromptRequestRequest: {
            /** @description User's casual description of what they want to generate */
            description: string;
            /** @default photorealistic */
            style: components["schemas"]["StyleEnum"];
        };
        /** @description Serializer for prompt refinement response. */
        RefinePromptResponse: {
            readonly refined_prompt: string;
            readonly negative_prompt: string;
        };
        /** @description Serializer for a related image with similarity score. */
        RelatedImage: {
            readonly image: components["schemas"]["Image"];
            /** Format: double */
            readonly similarity_score: number;
        };
        RelatedImagesResponse: {
            count: number;
            results: components["schemas"]["RelatedImage"][];
        };
        ReorderResponse: {
            detail: string;
        };
        /** @description Request to apply a different style to an existing image. */
        RestyleRequestRequest: {
            style: components["schemas"]["StyleEnum"];
            /**
             * Format: double
             * @default 0.65
             */
            strength: number;
        };
        /**
         * @description * `user` - User
         *     * `assistant` - Assistant
         * @enum {string}
         */
        RoleEnum: "user" | "assistant";
        ServiceUnavailable: {
            detail: string;
        };
        SessionCreateRequest: {
            /** @default Nova sessão */
            title: string;
        };
        SessionMessage: {
            readonly id: number;
            readonly role: components["schemas"]["RoleEnum"];
            text: string;
            readonly image: number | null;
            /** Format: uri */
            readonly image_url: string | null;
            readonly prompt_used: string;
            /** Format: date-time */
            readonly created_at: string;
        };
        SessionMessageCreateRequest: {
            text: string;
        };
        /**
         * @description * `active` - Active
         *     * `archived` - Archived
         * @enum {string}
         */
        SessionStatusEnum: "active" | "archived";
        /**
         * @description * `photorealistic` - Fotorrealista
         *     * `anime` - Anime/Mangá
         *     * `digital_art` - Arte Digital
         *     * `oil_painting` - Pintura a Óleo
         *     * `watercolor` - Aquarela
         *     * `3d_render` - Render 3D
         *     * `pixel_art` - Pixel Art
         *     * `sketch` - Esboço/Desenho
         * @enum {string}
         */
        StyleEnum: "photorealistic" | "anime" | "digital_art" | "oil_painting" | "watercolor" | "3d_render" | "pixel_art" | "sketch";
        /** @description Serializer for a style suggestion. */
        StyleSuggestion: {
            readonly label: string;
            readonly example_prompt: string;
            readonly example_image_id: number;
            readonly frequency: number;
            /** Format: double */
            readonly confidence: number;
        };
        StyleSuggestionsResponse: {
            count: number;
            results: components["schemas"]["StyleSuggestion"][];
        };
        TokenObtainPair: {
            readonly access: string;
            readonly refresh: string;
        };
        TokenObtainPairRequest: {
            email: string;
            password: string;
        };
        TokenRefresh: {
            readonly access: string;
            refresh: string;
        };
        TokenRefreshRequest: {
            refresh: string;
        };
        TokenVerifyRequest: {
            token: string;
        };
        /** @description Serializer for user details. */
        User: {
            /** Format: uuid */
            readonly id: string;
            /** Format: email */
            readonly email: string;
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            username: string;
            first_name?: string;
            last_name?: string;
            bio?: string;
            readonly is_verified: boolean;
            readonly plan: string;
            readonly image_generation_count: number;
            profile_picture?: string | null;
            cover_picture?: string | null;
            preferences?: unknown;
            /** Format: uri */
            readonly avatar_url: string | null;
            /** Format: uri */
            readonly cover_url: string | null;
        };
        /** @description Serializer for user login. */
        UserLoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        /** @description Serializer for user registration. */
        UserRegistration: {
            /** Format: email */
            email: string;
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            username: string;
            first_name: string;
            last_name: string;
            /** @default  */
            bio: string;
        };
        /** @description Serializer for user registration. */
        UserRegistrationRequest: {
            /** Format: email */
            email: string;
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            username: string;
            password: string;
            password2: string;
            first_name: string;
            last_name: string;
            /** @default  */
            bio: string;
        };
        /** @description Serializer for user details. */
        UserRequest: {
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            username: string;
            first_name?: string;
            last_name?: string;
            bio?: string;
            profile_picture?: string | null;
            cover_picture?: string | null;
            preferences?: unknown;
        };
        /** @description Request to generate variations of an existing image. */
        VariationRequestRequest: {
            /** @default 1 */
            count: number;
            /**
             * Format: double
             * @default 0.65
             */
            strength: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_account_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailResponse"];
                };
            };
        };
    };
    auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserLoginRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["UserLoginRequest"];
                "multipart/form-data": components["schemas"]["UserLoginRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    auth_password_change_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ChangePasswordRequest"];
                "multipart/form-data": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailResponse"];
                };
            };
        };
    };
    auth_password_reset_confirm_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetConfirmRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PasswordResetConfirmRequest"];
                "multipart/form-data": components["schemas"]["PasswordResetConfirmRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailResponse"];
                };
            };
        };
    };
    auth_password_reset_request_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PasswordResetRequestRequest"];
                "multipart/form-data": components["schemas"]["PasswordResetRequestRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailResponse"];
                };
            };
        };
    };
    auth_preferences_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_preferences_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_profile_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    auth_profile_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["UserRequest"];
                "multipart/form-data": components["schemas"]["UserRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    auth_profile_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUserRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedUserRequest"];
                "multipart/form-data": components["schemas"]["PatchedUserRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    auth_profile_avatar_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailResponse"];
                };
            };
        };
    };
    auth_profile_cover_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailResponse"];
                };
            };
        };
    };
    auth_register_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRegistrationRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["UserRegistrationRequest"];
                "multipart/form-data": components["schemas"]["UserRegistrationRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRegistration"];
                };
            };
        };
    };
    auth_token_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefreshRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefreshRequest"];
                "multipart/form-data": components["schemas"]["TokenRefreshRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
    auth_verify_email_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailResponse"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetailResponse"];
                };
            };
        };
    };
    generate_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateImageRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["GenerateImageRequest"];
                "multipart/form-data": components["schemas"]["GenerateImageRequest"];
            };
        };
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Image"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateError"];
                };
            };
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuotaExceeded"];
                };
            };
        };
    };
    images_comments_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedImageCommentList"];
                };
            };
        };
    };
    images_comments_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImageCommentCreateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ImageCommentCreateRequest"];
                "multipart/form-data": components["schemas"]["ImageCommentCreateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageCommentCreate"];
                };
            };
        };
    };
    images_comments_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                comment_id: number;
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    images_comments_like_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                comment_id: number;
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentLikeResponse"];
                };
            };
        };
    };
    images_comments_like_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                comment_id: number;
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentUnlikeResponse"];
                };
            };
            /** @description No response body */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    images_download_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadResponse"];
                };
            };
            /** @description No response body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    images_like_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Image"];
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Image"];
                };
            };
        };
    };
    images_like_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LikeNotFound"];
                };
            };
        };
    };
    images_related_retrieve: {
        parameters: {
            query?: {
                /** @description Máximo de resultados (default 12, max 20) */
                limit?: number;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelatedImagesResponse"];
                };
            };
        };
    };
    images_restyle_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RestyleRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["RestyleRequestRequest"];
                "multipart/form-data": components["schemas"]["RestyleRequestRequest"];
            };
        };
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Image"];
                };
            };
        };
    };
    images_share_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Image"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFound"];
                };
            };
        };
    };
    images_share_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedImageShareUpdateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedImageShareUpdateRequest"];
                "multipart/form-data": components["schemas"]["PatchedImageShareUpdateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Image"];
                };
            };
            /** @description No response body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No response body */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    images_variations_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["VariationRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["VariationRequestRequest"];
                "multipart/form-data": components["schemas"]["VariationRequestRequest"];
            };
        };
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Image"][];
                };
            };
        };
    };
    images_liked_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedImageList"];
                };
            };
        };
    };
    images_my_images_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedImageList"];
                };
            };
        };
    };
    images_public_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedImageList"];
                };
            };
        };
    };
    projects_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"][];
                };
            };
        };
    };
    projects_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ProjectCreateRequest"];
                "multipart/form-data": components["schemas"]["ProjectCreateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
        };
    };
    projects_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
        };
    };
    projects_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ProjectCreateRequest"];
                "multipart/form-data": components["schemas"]["ProjectCreateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
        };
    };
    projects_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    projects_images_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectImageAddRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ProjectImageAddRequest"];
                "multipart/form-data": components["schemas"]["ProjectImageAddRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectImageAdded"];
                };
            };
        };
    };
    projects_images_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    projects_images_remove_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                image_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectImageAddRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ProjectImageAddRequest"];
                "multipart/form-data": components["schemas"]["ProjectImageAddRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectImageAdded"];
                };
            };
        };
    };
    projects_images_remove_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                image_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    projects_images_reorder_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedProjectReorderRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedProjectReorderRequest"];
                "multipart/form-data": components["schemas"]["PatchedProjectReorderRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReorderResponse"];
                };
            };
        };
    };
    projects_public_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedProjectList"];
                };
            };
        };
    };
    refine_prompt_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefinePromptRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["RefinePromptRequestRequest"];
                "multipart/form-data": components["schemas"]["RefinePromptRequestRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefinePromptResponse"];
                };
            };
            /** @description No response body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceUnavailable"];
                };
            };
        };
    };
    sessions_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreativeSessionList"][];
                };
            };
        };
    };
    sessions_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["SessionCreateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["SessionCreateRequest"];
                "multipart/form-data": components["schemas"]["SessionCreateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreativeSession"];
                };
            };
        };
    };
    sessions_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreativeSession"];
                };
            };
        };
    };
    sessions_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    sessions_messages_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionMessageCreateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["SessionMessageCreateRequest"];
                "multipart/form-data": components["schemas"]["SessionMessageCreateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentResponse"];
                };
            };
        };
    };
    token_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenObtainPairRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenObtainPairRequest"];
                "multipart/form-data": components["schemas"]["TokenObtainPairRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenObtainPair"];
                };
            };
        };
    };
    token_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefreshRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefreshRequest"];
                "multipart/form-data": components["schemas"]["TokenRefreshRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
    token_verify_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenVerifyRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenVerifyRequest"];
                "multipart/form-data": components["schemas"]["TokenVerifyRequest"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    users_me_style_suggestions_retrieve: {
        parameters: {
            query?: {
                /** @description Máximo de sugestões (default 5, max 10) */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StyleSuggestionsResponse"];
                };
            };
        };
    };
}
