FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt requirements-worker.txt ./
RUN pip install --upgrade pip && pip install -r requirements-worker.txt

COPY . .

CMD ["celery", "-A", "imagAine.celery", "worker", "-l", "info"]
